
export const NAVIGATE_TO_SUGGESTION = 'NAVIGATE_TO_SUGGESTION';

export const REQUEST_SUGGESTIONS = 'REQUEST_SUGGESTIONS';
export const RECEIVE_SUGGESTIONS = 'RECEIVE_SUGGESTIONS';

export const REQUEST_A_SUGGESTION = 'REQUEST_A_SUGGESTION';
export const RECEIVE_A_SUGGESTION = 'RECEIVE_A_SUGGESTION';

export const LIKE_SUGGESTION = 'LIKE_SUGGESTION';
export const DISLIKE_SUGGESTION = 'DISLIKE_SUGGESTION';

export const ADDING_SUGGESTION = 'ADDING_SUGGESTION';
export const ADDED_SUGGESTION = 'ADDED_SUGGESTION';

export const QUERY_UPDATED = 'QUERY_UPDATED';
export const SEARCHING = 'SEARCHING';
export const SEARCH_FINISHED = 'SEARCH_FINISHED';
export const SEARCH_NO_RESULT = 'SEARCH_NO_RESULT';

export const OPEN_LOGIN = 'OPEN_LOGIN';
export const CLOSE_LOGIN = 'CLOSE_LOGIN';
export const OPEN_NEW = 'OPEN_NEW';
export const CLOSE_NEW = 'CLOSE_NEW';
export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';