version: '2'
services:
  db:
    image: mongo
    container_name: "suggestion-db"
    volumes:
      - "~/suggestion/db:/data/db"
    ports:
      - 27017:27017

  web:
    image: usvaltech/suggestion:latest
    command: "npm start"
    container_name: "suggestion-web"
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      AUTH0_SECRET: xIOzOMRQX8tBgDKds9iEZLMWb72H2qovgDzUldgDanmaHes3vzancY9-zz58O4Bw
      AUTH0_CLIENTID: ClohFBYJyM7q0Nc6y9tY5blht98wjaBw
      PORT: 3000
      NODE_ENV: development
